module.exports={
    configureWebpack:{
        resolve:{
           resolve:{
            alias:{
           'assets':'@/assets',  
           'assets':'@/assets',  
           'assets':'@/assets',  
           'assets':'@/assets',  
            }
            }
        }
    }
}